export default {
    StyleMensWearSvgLogo: require('./styleMensWearLogo.svg').default,
    ClothiQSvgLogo: require('./ClothiQ-logo.svg').default,
    StyleMensWearLogoForDrawer: require('./styleMensWearLogoForDrawer.svg').default,
    MenuCollapsible: require('./menu-collapsible.svg').default,
    SearchGrey: require('./search-grey.svg').default,
    ArrowLeftPrimary: require('./arrow-left-primary.svg').default,
    SelectChevronWhite: require('./select-chevron-white.svg').default,
    LogoutDark: require('./logout-dark.svg').default,
    ChangePasswordDark: require('./change-password-dark.svg').default,
    VisibilityShow: require('./password-show.svg').default,
    VisibilityHide: require('./password-hide.svg').default,
    InfoGrey: require('./info-grey.svg').default,
    CloseGrey: require('./close-grey.svg').default,
    ChevronUpGrey: require('./chevron-up-grey.svg').default,
    ChevronDownGrey: require('./chevron-down-grey.svg').default,
    NoDataFoundsvg: require('./no-data-found.svg').default,
    SvgLogo: require('./SvgLogo.svg').default,
}