export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  NOT_FOUND: '/not-found',
  // Customer Routes
  PRODUCTS: '/products',
  PRODUCT_DETAIL: '/products/:id',
  CART: '/cart',
  WISHLIST: '/wishlist',
  CHECKOUT: '/checkout',
  ORDER_CONFIRMATION: '/order-confirmation/:orderId',
  // Account Routes
  ACCOUNT: '/account',
  ACCOUNT_DASHBOARD: '/account/dashboard',
  ACCOUNT_ORDERS: '/account/orders',
  ACCOUNT_ORDER_DETAIL: '/account/orders/:orderId',
  ACCOUNT_WISHLIST: '/account/wishlist',
  ACCOUNT_REVIEWS: '/account/reviews',
  ACCOUNT_ADDRESSES: '/account/addresses',
  ACCOUNT_PAYMENTS: '/account/payments',
  ACCOUNT_SETTINGS: '/account/settings',
  ACCOUNT_NOTIFICATIONS: '/account/notifications',
  ACCOUNT_HELP: '/account/help',
  // Admin Routes
  ADMIN_DASHBOARD: '/admin/dashboard',
  ADMIN_CATEGORIES: '/admin/categories',
  ADMIN_PRODUCTS: '/admin/products',
  ADMIN_ORDERS: '/admin/orders',
  ADMIN_USERS: '/admin/users',
  ADMIN_SETTINGS: '/admin/settings',
}
